#!/usr/bin/env bash
set -e

echo "$USERSERVICE_DB_NAME $USERSERVICE_DB_USER"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $USERSERVICE_DB_USER WITH PASSWORD '$USERSERVICE_DB_PASSWORD';
	CREATE DATABASE $USERSERVICE_DB_NAME;
	GRANT ALL PRIVILEGES ON DATABASE $USERSERVICE_DB_NAME TO $USERSERVICE_DB_USER;
EOSQL
